data_sources:
  -
    type: 'StreamingAPI'
    alias: 'Twitter Streaming API'
    api_key: 'XXXXXXXXXXXXXXXXXXXXXXXX'
    api_secret: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    access_token: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    access_token_secret: 'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
    auto_restart: True
    projection:
        - 'text'
        - 'created_at'
        - 'lang'
    outputs:
        - 'Streaming Sentiment Classifier'
  -
    type: 'FlatFile'
    alias: 'Raw Tweets JSON File'
    filename: 'examples/sentiment-analysis/data/raw_tweets.json'
    outputs:
        - 'Flat File Sentiment Classifier'
models:
  -
    alias: 'Flat File Sentiment Classifier'
    module_file_path: 'examples/sentiment-analysis/sentiment.py'
    module_classname: 'SentimentClassifier'
    method_name: 'predict'
    output_attribute: 'sentiment_score'
    preprocessor: 'Tweet Preprocessor'
    outputs:
        - 'Twitter Sentiment Predictions File'
  -
    alias: 'Streaming Sentiment Classifier'
    module_file_path: 'examples/sentiment-analysis/sentiment.py'
    module_classname: 'SentimentClassifier'
    method_name: 'predict'
    output_attribute: 'sentiment_score'
    preprocessor: 'Tweet Preprocessor'
    outputs:
        - 'IO'
storage:
  -
    type: 'File'
    alias: 'Twitter Sentiment Predictions File'
    save_filename: 'sentiment_predictions.json'
  -
    type: 'IO'
    alias: 'stdout'
preprocessors:
  -
    alias: 'Tweet Preprocessor'
    module_file_path: 'examples/sentiment-analysis/tweet_preprocessor.py'
    module_classname: 'TweetPreprocessor'
    json_attribute: 'text'
    method_name: 'preprocess'
messaging:
    host: 'localhost'
