# Can be the following types: 'Socket', 'MessageQueue', 'StreamingAPI', 'HTTPAPI'
data_sources:
  - 
    # Socket stream incoming data is in JSON format
    source_type: 'Socket'
    source_alias: 'Local TCP Socket 123'
    ip_address: '192.168.0.1'
    port: 8081
    socket_type: 'TCP'
  - 
    source_type: 'MessageQueue'
    source_alias: 'My RabbitMQ message queue'
    host: 'localhost'
    queue_name: 'my_queue'
    ack_type: 'auto'
    durable: false

# Model types can be 'Classification', or 'Sentiment'
# Model service type can be either 'SERVICE' or 'DOWNLOAD'
models:
  - 
    model_type: 'Classification'
    model_service_type: 'DOWNLOAD'
    model_code: 'classificationModel.py'
    model_function: 'model.fit'
    # TODO: Add more fields here
  -
    model_type: 'Sentiment'
    model_service_type: 'SERVICE'
    host: 'localhost'
    port: 8082
    api: '/my_sentiment_api/'