# Can be the following types: 'Socket', 'MessageQueue', 'StreamingAPI', 'HTTPAPI'
data_sources:
  - 
    # Socket stream incoming data is in JSON format
    source_type: 'Socket'
    source_alias: 'Local TCP Socket 123'
    host: 'localhost' #richards-mbp-5.uconnect.utah.edu'
    port: 8081
    # May not need this -> socket_type: 'TCP'
  - 
    source_type: 'MessageQueue'
    source_alias: 'My RabbitMQ message queue'
    host: 'localhost'
    queue_name: 'my_queue'
    ack_type: 'auto'
    durable: false
  -
    source_type: 'StreamingAPI'
    source_alias: 'Twitter Streaming API'
    host: ''
    api_key: ''
    api_secret: ''
    access_token: ''
    access_token_secret: ''

# Model types can be 'Classification', or 'Sentiment'
# Model service type can be either 'SERVICE' or 'DOWNLOAD'
models:
  - 
    model_type: 'Classification'
    model_service_type: 'DOWNLOAD'
    model_code: 'classificationModel.py'
    model_build_function: 'model.build'
    model_fit_function: 'model.fit'
    mode_predict_function: 'model.predict'
    model_save_function: 'model.save'
    # TODO: Add more fields here
  -
    model_type: 'Sentiment'
    model_service_type: 'SERVICE'
    host: 'localhost'
    port: 8082
    api: '/my_sentiment_api/'